#!/bin/sh
# Install Sol Advisor's shipped custom-agent templates without changing Codex config.

set -eu

usage() {
  cat <<'EOF'
Usage: install-agents.sh [--target-dir PATH] [--check] [--sync]

Install Sol Advisor's two current custom-agent templates into the target directory.
Normal mode also migrates only exact known historical companion files: it replaces
legacy Terra templates and removes the legacy Luna template. It never overwrites a
modified, nonregular, or symlinked destination.

Without --target-dir, the target is "$CODEX_HOME/agents" when CODEX_HOME is already
set, otherwise "$HOME/.codex/agents".

Options:
  --target-dir PATH  Explicit destination directory (absolute or relative).
  --check            Verify that Terra and Sol match exactly and no legacy Luna file
                     remains; do not create, replace, or remove anything.
  --sync             Explicitly replace a previously dashboard-generated Terra or Sol
                     template after its local role assignment changed. Refuses files
                     not recognized as plugin-managed.
  --help             Show this help text.
EOF
}

fail() {
  printf '%s\n' "ERROR: $*" >&2
  exit 1
}

report_preflight_error() {
  printf '%s\n' "ERROR: $*" >&2
  preflight_failed=1
}

path_exists() {
  [ -e "$1" ] || [ -L "$1" ]
}

sha256_file() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" 2>/dev/null | awk 'NF >= 1 && length($1) == 64 { print $1; exit }'
  else
    sha256sum "$1" 2>/dev/null | awk 'NF >= 1 && length($1) == 64 { print $1; exit }'
  fi
}

sha256_stream() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 2>/dev/null | awk 'NF >= 1 && length($1) == 64 { print $1; exit }'
  else
    sha256sum 2>/dev/null | awk 'NF >= 1 && length($1) == 64 { print $1; exit }'
  fi
}

is_dashboard_managed() {
  destination=$1
  template=$2
  expected_role=''
  expected_digest=''
  actual_digest=''

  [ -f "$destination" ] && [ ! -L "$destination" ] || return 1
  [ "$(sed -n '1p' "$destination")" = '# Generated by Sol Advisor local role dashboard. Do not edit manually.' ] || return 1
  expected_role=$(sed -n 's/^name = "\([A-Za-z0-9_]*\)"$/\1/p' "$template")
  [ -n "$expected_role" ] || return 1
  grep -Fqx "name = \"$expected_role\"" "$destination" || return 1
  expected_digest=$(sed -n '2p' "$destination" | sed -n 's/^# sol-advisor-role-map-sha256: \([0-9a-f]\{64\}\)$/\1/p')
  [ -n "$expected_digest" ] || return 1
  # The dashboard writes LF, but Git may check out a plugin source with CRLF on
  # Windows. Hash normalized lines so line-ending conversion does not turn an intact
  # plugin-managed template into an unknown file.
  if command -v python3 >/dev/null 2>&1; then
    digest_python=python3
  else
    digest_python=python
  fi
  actual_digest=$("$digest_python" - "$destination" <<'PY' | sha256_stream
from pathlib import Path
import sys

payload = Path(sys.argv[1]).read_bytes().splitlines(keepends=True)[2:]
normalized = b"".join(line.rstrip(b"\r\n") + b"\n" for line in payload)
sys.stdout.buffer.write(normalized)
PY
)
  [ -n "$actual_digest" ] && [ "$expected_digest" = "$actual_digest" ]
}

classify_current_or_legacy() {
  destination=$1
  template=$2
  legacy_digest=$3
  prior_digest=$4

  if ! path_exists "$destination"; then
    printf '%s\n' missing
  elif [ -L "$destination" ] || [ ! -f "$destination" ]; then
    printf '%s\n' unsafe
  elif cmp -s "$template" "$destination"; then
    printf '%s\n' current
  else
    digest=$(sha256_file "$destination")
    if [ -n "$legacy_digest" ] && [ "$digest" = "$legacy_digest" ]; then
      printf '%s\n' legacy
    elif [ -n "$prior_digest" ] && [ "$digest" = "$prior_digest" ]; then
      printf '%s\n' prior
    elif is_dashboard_managed "$destination" "$template"; then
      printf '%s\n' dashboard
    elif [ -z "$digest" ]; then
      printf '%s\n' unreadable
    else
      printf '%s\n' conflict
    fi
  fi
}

classify_legacy_luna() {
  destination=$1

  if ! path_exists "$destination"; then
    printf '%s\n' missing
  elif [ -L "$destination" ] || [ ! -f "$destination" ]; then
    printf '%s\n' unsafe
  else
    digest=$(sha256_file "$destination")
    if [ "$digest" = "$legacy_luna_sha256" ]; then
      printf '%s\n' legacy
    elif [ -z "$digest" ]; then
      printf '%s\n' unreadable
    else
      printf '%s\n' conflict
    fi
  fi
}

same_state() {
  label=$1
  expected=$2
  actual=$3
  [ "$expected" = "$actual" ] || fail "$label changed after preflight; no further destination files were changed."
}

install_missing() {
  template=$1
  destination=$2
  staged=''

  if path_exists "$destination"; then
    fail "destination changed after preflight and will not be overwritten: $destination"
  fi

  staged=$(mktemp "$target_dir/.sol-advisor-agent.XXXXXX") || fail "could not stage template for installation: $destination"
  if ! cp "$template" "$staged"; then
    rm -f "$staged"
    fail "could not stage template for installation: $destination"
  fi

  if ! ln "$staged" "$destination"; then
    rm -f "$staged"
    fail "destination changed after preflight and will not be overwritten: $destination"
  fi

  rm -f "$staged" || fail "could not remove staged template after installation: $staged"
  printf '%s\n' "INSTALLED: $destination"
}

replace_legacy_terra() {
  staged=''

  [ "$(classify_current_or_legacy "$terra_destination" "$terra_template" "$legacy_terra_sha256" "$prior_terra_sha256")" = legacy ] ||
    fail "legacy Terra destination changed after preflight and will not be replaced: $terra_destination"

  staged=$(mktemp "$target_dir/.sol-advisor-agent.XXXXXX") || fail "could not stage migrated Terra template: $terra_destination"
  if ! cp "$terra_template" "$staged"; then
    rm -f "$staged"
    fail "could not stage migrated Terra template: $terra_destination"
  fi

  [ "$(classify_current_or_legacy "$terra_destination" "$terra_template" "$legacy_terra_sha256" "$prior_terra_sha256")" = legacy ] || {
    rm -f "$staged"
    fail "legacy Terra destination changed after preflight and will not be replaced: $terra_destination"
  }

  if ! mv -f "$staged" "$terra_destination"; then
    rm -f "$staged"
    fail "could not replace exact legacy Terra template: $terra_destination"
  fi

  printf '%s\n' "MIGRATED: $terra_destination"
}

replace_managed_template() {
  label=$1
  template=$2
  destination=$3
  state=$4
  legacy_digest=$5
  prior_digest=$6
  preflight_digest=$7
  staged=''

  case "$state" in
    prior|dashboard) ;;
    *) fail "$label destination is not a recognized plugin-managed template: $destination" ;;
  esac

  staged=$(mktemp "$target_dir/.sol-advisor-agent.XXXXXX") || fail "could not stage synced template: $destination"
  if ! cp "$template" "$staged"; then
    rm -f "$staged"
    fail "could not stage synced template: $destination"
  fi

  case "$state" in
    prior)
      current_state=$(classify_current_or_legacy "$destination" "$template" "$legacy_digest" "$prior_digest")
      ;;
    dashboard)
      if is_dashboard_managed "$destination" "$template"; then current_state=dashboard; else current_state=changed; fi
      ;;
  esac
  if [ "$current_state" != "$state" ]; then
    rm -f "$staged"
    fail "$label destination changed after preflight and will not be overwritten: $destination"
  fi
  [ "$(sha256_file "$destination")" = "$preflight_digest" ] || {
    rm -f "$staged"
    fail "$label destination contents changed after preflight and will not be overwritten: $destination"
  }

  if ! mv -f "$staged" "$destination"; then
    rm -f "$staged"
    fail "could not sync plugin-managed template: $destination"
  fi
  printf '%s\n' "SYNCED: $destination"
}

remove_legacy_luna() {
  [ "$(classify_legacy_luna "$luna_destination")" = legacy ] ||
    fail "legacy Luna destination changed after preflight and will not be removed: $luna_destination"
  rm "$luna_destination" || fail "could not remove exact legacy Luna template: $luna_destination"
  printf '%s\n' "REMOVED LEGACY: $luna_destination"
}

script_dir=$(CDPATH= cd "$(dirname "$0")" && pwd) || exit 1
template_dir=$script_dir/../agents

if [ -n "${CODEX_HOME-}" ]; then
  target_dir=$CODEX_HOME/agents
else
  [ -n "${HOME-}" ] || fail "HOME is unset and CODEX_HOME was not supplied; pass --target-dir explicitly."
  target_dir=$HOME/.codex/agents
fi

check_only=0
sync_requested=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --target-dir)
      [ "$#" -ge 2 ] || fail "--target-dir requires a path."
      [ -n "$2" ] || fail "--target-dir requires a non-empty path."
      case "$2" in
        --*) fail "--target-dir path must be explicit; prefix an option-like relative name with ./ or use an absolute path." ;;
      esac
      target_dir=$2
      shift 2
      ;;
    --check)
      check_only=1
      shift
      ;;
    --sync)
      sync_requested=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1 (run with --help for usage)."
      ;;
  esac
done

[ "$check_only" -eq 0 ] || [ "$sync_requested" -eq 0 ] ||
  fail "--check and --sync cannot be used together."

case "$target_dir" in
  /*) ;;
  *) target_dir=$(pwd -P)/$target_dir ;;
esac

case "$target_dir" in
  /|//) fail "refusing to use the filesystem root as an agent target directory." ;;
esac

terra_file=sol-advisor-terra-implementer.toml
sol_file=sol-advisor-sol-reviewer.toml
luna_file=sol-advisor-luna-implementer.toml
terra_template=$template_dir/$terra_file
sol_template=$template_dir/$sol_file
terra_destination=$target_dir/$terra_file
sol_destination=$target_dir/$sol_file
luna_destination=$target_dir/$luna_file

# Immutable v0.2.0 byte digests, calculated from:
# git show HEAD:plugins/sol-advisor/agents/sol-advisor-luna-implementer.toml | shasum -a 256
# git show HEAD:plugins/sol-advisor/agents/sol-advisor-terra-implementer.toml | shasum -a 256
legacy_luna_sha256=fba1b42849d93737e83b094a2ab0b1611f87ac37db7438c8bbdf581f0813f8eb
legacy_terra_sha256=4425a8c1f21ce8c6af93f96adc253bbc33ea301f1389b3fa8ce350be08584eca
# Exact prior-state templates (current rendering without the dashboard header).
# These are safe one-time upgrade inputs, not a permission to replace a
# user-modified agent file.
prior_terra_sha256=06c318e5e93f37452635906394e6ea69fb6a65ba9e6ad7172d37b444e0dc871d
prior_sol_sha256=0333acf0ef562bcfebd06009ac09bd1dd8cbc04c4cf28e08e9e049bd8bf202d2

for template in "$terra_template" "$sol_template"; do
  [ -f "$template" ] && [ ! -L "$template" ] ||
    fail "shipped template is missing or not a regular file: $template"
done

preflight_failed=0
if path_exists "$target_dir"; then
  if [ -L "$target_dir" ] || [ ! -d "$target_dir" ]; then
    report_preflight_error "target directory is not a real directory: $target_dir"
  fi
fi

terra_state=$(classify_current_or_legacy "$terra_destination" "$terra_template" "$legacy_terra_sha256" "$prior_terra_sha256")
sol_state=$(classify_current_or_legacy "$sol_destination" "$sol_template" '' "$prior_sol_sha256")
luna_state=$(classify_legacy_luna "$luna_destination")
terra_destination_digest=$(sha256_file "$terra_destination")
sol_destination_digest=$(sha256_file "$sol_destination")

if [ "$check_only" -eq 1 ]; then
  [ "$terra_state" = current ] ||
    report_preflight_error "Terra template is $terra_state, not the current exact file: $terra_destination"
  [ "$sol_state" = current ] ||
    report_preflight_error "Sol template is $sol_state, not the current exact file: $sol_destination"
  [ "$luna_state" = missing ] ||
    report_preflight_error "legacy Luna file remains or is unsafe: $luna_destination"
else
  if [ "$sync_requested" -eq 1 ]; then
    case "$terra_state" in
      current|legacy|prior|dashboard|missing) ;;
      *) report_preflight_error "Terra destination is $terra_state and will not be replaced: $terra_destination" ;;
    esac
    case "$sol_state" in
      current|prior|dashboard|missing) ;;
      *) report_preflight_error "Sol destination is $sol_state and will not be replaced: $sol_destination" ;;
    esac
  else
    case "$terra_state" in
      current|legacy|missing) ;;
      *) report_preflight_error "Terra destination is $terra_state and will not be replaced without --sync: $terra_destination" ;;
    esac
    case "$sol_state" in
      current|missing) ;;
      *) report_preflight_error "Sol destination is $sol_state and will not be replaced without --sync: $sol_destination" ;;
    esac
  fi
  case "$luna_state" in
    missing|legacy) ;;
    *) report_preflight_error "legacy Luna destination is $luna_state and will not be removed: $luna_destination" ;;
  esac
fi

[ "$preflight_failed" -eq 0 ] || exit 1

if [ "$check_only" -eq 1 ]; then
  printf '%s\n' "CHECK PASSED: Terra and Sol exactly match $template_dir; no legacy Luna file remains."
  exit 0
fi

if [ ! -d "$target_dir" ]; then
  mkdir -p "$target_dir" || fail "could not create target directory: $target_dir"
fi
[ -d "$target_dir" ] && [ ! -L "$target_dir" ] ||
  fail "target directory changed after preflight: $target_dir"

same_state Terra "$terra_state" "$(classify_current_or_legacy "$terra_destination" "$terra_template" "$legacy_terra_sha256" "$prior_terra_sha256")"
same_state Sol "$sol_state" "$(classify_current_or_legacy "$sol_destination" "$sol_template" '' "$prior_sol_sha256")"
same_state "legacy Luna" "$luna_state" "$(classify_legacy_luna "$luna_destination")"

case "$terra_state" in
  missing) install_missing "$terra_template" "$terra_destination" ;;
  legacy) replace_legacy_terra ;;
  prior) replace_managed_template Terra "$terra_template" "$terra_destination" "$terra_state" "$legacy_terra_sha256" "$prior_terra_sha256" "$terra_destination_digest" ;;
  dashboard) replace_managed_template Terra "$terra_template" "$terra_destination" "$terra_state" "$legacy_terra_sha256" "$prior_terra_sha256" "$terra_destination_digest" ;;
  current) printf '%s\n' "ALREADY CURRENT: $terra_destination" ;;
esac

case "$sol_state" in
  missing) install_missing "$sol_template" "$sol_destination" ;;
  prior) replace_managed_template Sol "$sol_template" "$sol_destination" "$sol_state" '' "$prior_sol_sha256" "$sol_destination_digest" ;;
  dashboard) replace_managed_template Sol "$sol_template" "$sol_destination" "$sol_state" '' "$prior_sol_sha256" "$sol_destination_digest" ;;
  current) printf '%s\n' "ALREADY CURRENT: $sol_destination" ;;
esac

if [ "$luna_state" = legacy ]; then
  remove_legacy_luna
fi

[ "$(classify_current_or_legacy "$terra_destination" "$terra_template" "$legacy_terra_sha256" "$prior_terra_sha256")" = current ] ||
  fail "post-install exactness check failed: $terra_destination"
[ "$(classify_current_or_legacy "$sol_destination" "$sol_template" '' "$prior_sol_sha256")" = current ] ||
  fail "post-install exactness check failed: $sol_destination"
[ "$(classify_legacy_luna "$luna_destination")" = missing ] ||
  fail "post-install legacy removal check failed: $luna_destination"

printf '%s\n' "INSTALL PASSED: Terra and Sol exactly match $template_dir; no legacy Luna file remains."
